In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [15]:
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
#tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
#dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [25]:
np.array([1,0,3],dtype = bool)

array([ True, False,  True])

In [27]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [31]:
#np.arrange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [35]:
#with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.random.random((3,4))

array([[0.76799219, 0.4114272 , 0.29922747, 0.58355667],
       [0.6120969 , 0.72092214, 0.29884347, 0.53887605],
       [0.22444202, 0.72526   , 0.84246956, 0.96347398]])

In [59]:
#np.linspace(linearly spaced)
np.linspace(-10,10,10)#10 se 10 tk 10 random no. generate kar ke do

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [63]:
#np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
a2 = np.arange(12,dtype = float)#vector
a2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [67]:
a2.reshape(3,4)#matrix

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [69]:
a2 = np.arange(12,dtype = float).reshape(2,6)
a2

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [75]:
a3 = np.arange(16).reshape(2,2,4)# no. of blocks,row in each block,columns in each block
a3# tensor

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [79]:
#ndim
a2.ndim

2

In [81]:
a3.shape

(2, 2, 4)

In [83]:
a3.ndim

3

In [87]:
a4 = np.arange(16).reshape(2,2,2,2)
a4# 2 blocks,2 groups ,2 rows,2 columns

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [89]:
a4.ndim

4

In [91]:
#size
print(a3.size)

16


In [93]:
#Itemsize
a3.itemsize

4

In [95]:
a2.itemsize

8

In [97]:
#dtype
print(a2.dtype)
print(a3.dtype)

float64
int32


In [103]:
a3.astype(np.int32)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]], dtype=int64)

In [105]:
print(a3.dtype)

int32


In [115]:
a1 = np.arange(12,24).reshape(4,3)
a1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [117]:
#scalar operations
#arithmetic
a1*2

array([[24, 26, 28],
       [30, 32, 34],
       [36, 38, 40],
       [42, 44, 46]])

In [119]:
a1/2

array([[ 6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. ],
       [10.5, 11. , 11.5]])

In [121]:
#relational 
a2>5

array([[False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True]])

In [125]:
a1>15

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [133]:
#vector operations
#arithmetic
a4 = np.arange(12,24).reshape(4,3)
a4+a1

array([[24, 26, 28],
       [30, 32, 34],
       [36, 38, 40],
       [42, 44, 46]])

In [139]:
a5 = np.random.random(3)
a5

array([0.87861403, 0.12467447, 0.78350704])

In [145]:
a6 = np.random.random((3,2))
a6

array([[0.95703876, 0.44891978],
       [0.00256442, 0.80092411],
       [0.57940754, 0.51413762]])

In [147]:
np.max(a5)

0.8786140254993943

In [149]:
np.sum(a4)

210

In [151]:
# to calculate minimum of each row   0-> column, 1->row
np.max(a1,axis = 0)

array([21, 22, 23])

In [153]:
np.min(a1,axis=1)

array([12, 15, 18, 21])

In [155]:
#statistical  =>mean/median/mode/std/var
np.mean(a1)

17.5

In [157]:
np.median(a1)

17.5

In [159]:
np.std(a1)

3.452052529534663

In [161]:
#trignometric functions
np.sin(a1)

array([[-0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749],
       [-0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 ]])

In [163]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [165]:
np.log(a1)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [167]:
np.exp(a1)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [171]:
#rounf/floor/ceil
np.round(np.random.random((2,3))*100)

array([[30., 62., 78.],
       [95., 22., 67.]])

In [173]:
np.floor(np.random.random((2,3))*100)

array([[ 8., 29., 53.],
       [11., 96., 37.]])

In [175]:
#indexing and slicing
a1[1,2]

17

In [191]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [193]:
a3[1,0,1]

5

In [195]:
a3[0,1,0]

2

In [197]:
a3[0,0,0]

0

In [207]:
a1 = np.arange(12)
a1[2:5]

array([2, 3, 4])

In [209]:
a1[2:8:2]

array([2, 4, 6])

In [211]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [213]:
a2[0,:]

array([0, 1, 2, 3])

In [215]:
a2[:,2]

array([ 2,  6, 10])

In [217]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [223]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [227]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [229]:
a2[1,1:]

array([5, 6, 7])

In [237]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [239]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [243]:
a3[0,1,:]

array([3, 4, 5])

In [245]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [247]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [253]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [257]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [259]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [261]:
#ravel => conver any dim srray to 1 d rray
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [267]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [269]:
#horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [271]:
#vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [275]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [277]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [283]:
np.vsplit(a4,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]