In [1]:
lst=[]
print(type(lst))

<class 'list'>


In [2]:
names=["nishu",3,"a"]
print(names)
print(names[0])

['nishu', 3, 'a']
nishu


### accessing list


In [ ]:
names[0]

'nishu'

In [5]:
import numpy as np

arr = np.random.rand(2, 2)*100
print(arr)


[[20.10347563 55.61669511]
 [77.09264682 51.22968371]]


In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b       # [5 7 9]



array([5, 7, 9])

In [9]:
a - b       # [-3 -3 -3]


array([-3, -3, -3])

In [10]:
a * b       # [4 10 18]

array([ 4, 10, 18])

In [15]:
import numpy as np, time

lst = list(range(1000000))
arr = np.arange(1000000)

start = time.time()
print(start)
[x*2 for x in lst]
t2=time.time()
print(t2)
print("List:", t2-start)

start = time.time()
arr*2
print("NumPy:", time.time()-start)


1762067562.4432778
1762067562.4890838
List: 0.045805931091308594
NumPy: 0.002490520477294922
